import React,{useEffect,useRef,useState} from 'react';
import {loadMap} from './assets.js';
import MapCanvas from './MapCanvas.jsx';
import {label} from './names.js';
const bases=[['water','水基底','WATER'],['oil','油基底','OIL'],['wine','酒基底','WINE']];
function Icon({type}){if(type==='plus'||type==='minus')return <img className="control-icon" src={`/data/ui-${type}.webp`} alt=""/>;return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{type==='fit'?<path d="M9 4H4v5m11-5h5v5M4 15v5h5m11-5v5h-5"/>:type==='target'?<><circle cx="12" cy="12" r="6"/><path d="M12 2v4m0 12v4M2 12h4m12 0h4"/></>:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>}</svg>}
export default function App(){
  const [base,setBase]=useState('water'),[data,setData]=useState(null),[error,setError]=useState(''),[progress,setProgress]=useState(0),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[view,setView]=useState({scale:4}),[options,setOptions]=useState({labels:true,vortex:true,experience:true}),[mobileList,setMobileList]=useState(false);
  const mapRef=useRef(null);
  useEffect(()=>{let active=true;setData(null);setProgress(0);setError('');setSelected(null);loadMap(base,p=>{if(active)setProgress(p);}).then(result=>{if(active)setData(result);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[base]);
  const effects=(data?.map.effects||[]).filter(e=>`${label(e.id)} ${e.id}`.toLowerCase().includes(query.trim().toLowerCase()));
  function select(effect){setSelected(effect);mapRef.current?.focus(effect);setMobileList(false);}
  return <div className="app">
    <header className="header"><div className="brand"><div className="brand-symbol"><svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M12 4h8m-7 0v8L6 24q-2 4 3 4h14q5 0 3-4l-7-12V4M10 20h12"/><path d="m13 23 2-1m4 3h1"/></svg></div><div><h1>Potion Craft</h1><p>完整药剂地图</p></div></div><nav aria-label="地图基底">{bases.map(([id,title,en])=><button key={id} className={`base-tab ${id===base?'active':''}`} onClick={()=>{setBase(id);setQuery('');}} aria-pressed={id===base}><img className="base-icon" src={`/data/ui-${id}.webp`} alt=""/><span>{title}</span><small>{en}</small></button>)}</nav><button className="mobile-toggle" onClick={()=>setMobileList(!mobileList)} aria-expanded={mobileList}>药剂列表</button><div className="header-note">炼金术师的地图册</div></header>
    <div className="workspace"><aside className={`sidebar ${mobileList?'open':''}`}><div className="sidebar-heading"><h2>药剂效果</h2><span>{data?.map.effects.length||'—'} 个</span></div><label className="search"><Icon type="search"/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称或英文名" aria-label="搜索药剂"/></label><div className="effect-list">{effects.map(effect=><button className={`effect-row ${selected?.id===effect.id?'selected':''}`} key={effect.id} onClick={()=>select(effect)}><img src={`/data/${data.catalog.icons[effect.id].url}`} alt=""/><span><strong>{label(effect.id)}</strong><small>{effect.id}</small></span><span className="row-arrow">↗</span></button>)}{data&&effects.length===0?<p className="empty">没有找到这个药剂效果</p>:null}</div><div className="layers"><h3>地图图层</h3>{[['labels','药剂名称'],['vortex','漩涡与出口'],['experience','经验书']].map(([key,title])=><label key={key}><input type="checkbox" checked={options[key]} onChange={e=>setOptions(p=>({...p,[key]:e.target.checked}))}/><span>{title}</span></label>)}</div><p className="sidebar-foot">点击药剂，定位到地图上的效果点。</p></aside>
    <main className="map-area"><div className="map-caption"><span>{bases.find(b=>b[0]===base)[1]}</span><span>全部区域 · 无探索迷雾</span></div>{data?<MapCanvas ref={mapRef} data={data} options={options} selected={selected} onSelect={setSelected} onView={setView}/>:<div className="loading" role="status">{error?<><strong>地图加载失败</strong><span>{error}</span><button onClick={()=>location.reload()}>重新加载</button></>:<><div className="loading-ring"/><strong>正在展开地图</strong><span>加载原始地图素材 · {Math.round(progress*100)}%</span></>}</div>}
      <div className="zoom-controls"><button onClick={()=>mapRef.current?.zoom(1.4)} aria-label="放大"><Icon type="plus"/></button><output aria-label="缩放比例">{Math.round(view.scale)}%</output><button onClick={()=>mapRef.current?.zoom(1/1.4)} aria-label="缩小"><Icon type="minus"/></button><div className="control-divider"/><button onClick={()=>mapRef.current?.fit()} aria-label="查看全图" title="查看全图 (0)"><Icon type="fit"/></button><button onClick={()=>mapRef.current?.origin()} aria-label="回到起点" title="回到起点"><Icon type="target"/></button></div>
      {selected?<div className="detail"><img src={`/data/${data.catalog.icons[selected.id].url}`} alt=""/><div><strong>{label(selected.id)}</strong><span>坐标 {selected.x.toFixed(2)}, {(-selected.y).toFixed(2)} · 旋转 {Math.round(selected.rotation)}°</span></div><button aria-label="关闭药剂详情" onClick={()=>setSelected(null)}>×</button></div>:null}
      <div className="map-hint">拖拽移动 <span>·</span> 滚轮缩放 <span>·</span> 双击放大</div>
    </main></div><footer><span>水、油、酒 · 完整场景地图</span><span>游戏资源本地还原 <span className="footer-dot">·</span> {data?`${data.map.instanceCount.toLocaleString()} 个素材实例`:'正在加载'}</span><span><kbd>+</kbd><kbd>−</kbd> 缩放 <kbd>0</kbd> 全图</span></footer>
  </div>;
}



